version: '3'

services:
  python-dev:
    build:
      context: ./python-dev
    restart: always
    volumes:
      - ./root:/root

deploy:
  resources:
    limits:
      cpus: '24'
      memory: 96G
